language: python

sudo: false

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.8
      env:
        - TOX_ENV=py38

addons:
  apt:
    packages:
      - libdb-dev

install: pip install -U tox codecov

script: tox -e $TOX_ENV

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: redapple
  password:
    secure: pw5znAlmTbdg+AbWe2ixZ/fa3YBGnuNGCERz0lXkhZpuH6C6g1y/yzepx/dk5TY2QWrebia98nKeoNdvEoCpqU+e3qhqbqIEdIK9Fk1ISs1hrC4L1/qfDqAQ9vfCsPw9GgoQmIGlrCqSxGQDhY/AxdbNpaHcq4zUXz8IhPKcSulzkr2nMunTS47LSMa+rdK5kua/xDJatlCq/PbjbVlvrvyuOEFryu0yBMEonSvm5cdWagy42RWnOCRqdzlYxzdkV07SPGc8cehpKoaOIbFkkv2rDf6wU4pDOLlwcVPs/aKRxlxVpEGtHjkMMFT3NsWs95c/yVT50mQXuYsv0jNNYaMaQ6x43yDIVGYyKYyOJo9DAJCWyu8vyHmuQv2YjCpNKXfigWoB8h6MNi6VKG36+xm8mfZlRWENjKF1O7VmrsKv2n68MIfBpSDb/HkGSK3DeY0Hgqkv7f3cc0vyIZpzmrnFNqtPUjukqiSZJR6U24OlCEWh3R8X6USvMiS7dJd2GdhojU0UXbfT1oMI6SWpzKzg//eXTw769MG2TeTs9vFyLWc5RpmZzUmTzGOcoBlH4YZw852AqjhwcukW5ieK43aXS9HDJunHrtWbl791vU5XuAg1/0iauxTll1bJ0uF38JWakq5tnk/lf7ufBQBizfEcqiSDOcomHK2M+VWQTMg=
  on:
    tags: true
    repo: scrapy-plugins/scrapy-deltafetch
    condition: $TOXENV = py38
